/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

Expr  pExpr(FILE *inp);
Expr psExpr(const char *str);
Term  pTerm(FILE *inp);
Term psTerm(const char *str);
Factor  pFactor(FILE *inp);
Factor psFactor(const char *str);
Stmt  pStmt(FILE *inp);
Stmt psStmt(const char *str);

#endif
