/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printExpr(Expr p)
{
  _n_ = 0;
  bufReset();
  ppExpr(p, 0);
  return buf_;
}
char *printTerm(Term p)
{
  _n_ = 0;
  bufReset();
  ppTerm(p, 0);
  return buf_;
}
char *printFactor(Factor p)
{
  _n_ = 0;
  bufReset();
  ppFactor(p, 0);
  return buf_;
}
char *printStm(Stm p)
{
  _n_ = 0;
  bufReset();
  ppStm(p, 0);
  return buf_;
}
char *showExpr(Expr p)
{
  _n_ = 0;
  bufReset();
  shExpr(p);
  return buf_;
}
char *showTerm(Term p)
{
  _n_ = 0;
  bufReset();
  shTerm(p);
  return buf_;
}
char *showFactor(Factor p)
{
  _n_ = 0;
  bufReset();
  shFactor(p);
  return buf_;
}
char *showStm(Stm p)
{
  _n_ = 0;
  bufReset();
  shStm(p);
  return buf_;
}
void ppExpr(Expr p, int _i_)
{
  switch(p->kind)
  {
  case is_EAdd:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.eadd_.expr_, 0);
    renderC('+');
    ppTerm(p->u.eadd_.term_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ESub:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.esub_.expr_, 0);
    renderC('-');
    ppTerm(p->u.esub_.term_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void ppTerm(Term p, int _i_)
{
  switch(p->kind)
  {
  case is_TMul:
    if (_i_ > 0) renderC(_L_PAREN);
    ppTerm(p->u.tmul_.term_, 0);
    renderC('*');
    ppFactor(p->u.tmul_.factor_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TDiv:
    if (_i_ > 0) renderC(_L_PAREN);
    ppTerm(p->u.tdiv_.term_, 0);
    renderC('/');
    ppFactor(p->u.tdiv_.factor_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TExpr:
    if (_i_ > 0) renderC(_L_PAREN);
    ppFactor(p->u.texpr_.factor_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Term!\n");
    exit(1);
  }
}

void ppFactor(Factor p, int _i_)
{
  switch(p->kind)
  {
  case is_FInt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.fint_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FVar:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.fvar_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FStr:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.fstr_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FPar:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('(');
    ppExpr(p->u.fpar_.expr_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FIndex:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.findex_.ident_, 0);
    renderC('[');
    ppExpr(p->u.findex_.expr_, 0);
    renderC(']');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Factor!\n");
    exit(1);
  }
}

void ppStm(Stm p, int _i_)
{
  switch(p->kind)
  {
  case is_Assign:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.assign_.ident_, 0);
    renderC('=');
    ppExpr(p->u.assign_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ArrAssign:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.arrassign_.ident_, 0);
    renderC('[');
    ppExpr(p->u.arrassign_.expr_1, 0);
    renderC(']');
    renderC('=');
    ppExpr(p->u.arrassign_.expr_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Print:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("print");
    ppExpr(p->u.print_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Stm!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void ppInteger(String s, int i)
{
  renderS(s);
}


void ppIdent(String s, int i)
{
  renderS(s);
}


void ppString(String s, int i)
{
  renderS(s);
}


void shExpr(Expr p)
{
  switch(p->kind)
  {
  case is_EAdd:
    bufAppendC('(');

    bufAppendS("EAdd");

    bufAppendC(' ');

    shExpr(p->u.eadd_.expr_);
  bufAppendC(' ');
    shTerm(p->u.eadd_.term_);

    bufAppendC(')');

    break;
  case is_ESub:
    bufAppendC('(');

    bufAppendS("ESub");

    bufAppendC(' ');

    shExpr(p->u.esub_.expr_);
  bufAppendC(' ');
    shTerm(p->u.esub_.term_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Expr!\n");
    exit(1);
  }
}

void shTerm(Term p)
{
  switch(p->kind)
  {
  case is_TMul:
    bufAppendC('(');

    bufAppendS("TMul");

    bufAppendC(' ');

    shTerm(p->u.tmul_.term_);
  bufAppendC(' ');
    shFactor(p->u.tmul_.factor_);

    bufAppendC(')');

    break;
  case is_TDiv:
    bufAppendC('(');

    bufAppendS("TDiv");

    bufAppendC(' ');

    shTerm(p->u.tdiv_.term_);
  bufAppendC(' ');
    shFactor(p->u.tdiv_.factor_);

    bufAppendC(')');

    break;
  case is_TExpr:
    bufAppendC('(');

    bufAppendS("TExpr");

    bufAppendC(' ');

    shFactor(p->u.texpr_.factor_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Term!\n");
    exit(1);
  }
}

void shFactor(Factor p)
{
  switch(p->kind)
  {
  case is_FInt:
    bufAppendC('(');

    bufAppendS("FInt");

    bufAppendC(' ');

    shInteger(p->u.fint_.integer_);

    bufAppendC(')');

    break;
  case is_FVar:
    bufAppendC('(');

    bufAppendS("FVar");

    bufAppendC(' ');

    shIdent(p->u.fvar_.ident_);

    bufAppendC(')');

    break;
  case is_FStr:
    bufAppendC('(');

    bufAppendS("FStr");

    bufAppendC(' ');

    shString(p->u.fstr_.string_);

    bufAppendC(')');

    break;
  case is_FPar:
    bufAppendC('(');

    bufAppendS("FPar");

    bufAppendC(' ');

    shExpr(p->u.fpar_.expr_);

    bufAppendC(')');

    break;
  case is_FIndex:
    bufAppendC('(');

    bufAppendS("FIndex");

    bufAppendC(' ');

    shIdent(p->u.findex_.ident_);
  bufAppendC(' ');
    shExpr(p->u.findex_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Factor!\n");
    exit(1);
  }
}

void shStm(Stm p)
{
  switch(p->kind)
  {
  case is_Assign:
    bufAppendC('(');

    bufAppendS("Assign");

    bufAppendC(' ');

    shIdent(p->u.assign_.ident_);
  bufAppendC(' ');
    shExpr(p->u.assign_.expr_);

    bufAppendC(')');

    break;
  case is_ArrAssign:
    bufAppendC('(');

    bufAppendS("ArrAssign");

    bufAppendC(' ');

    shIdent(p->u.arrassign_.ident_);
  bufAppendC(' ');
    shExpr(p->u.arrassign_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.arrassign_.expr_2);

    bufAppendC(')');

    break;
  case is_Print:
    bufAppendC('(');

    bufAppendS("Print");

    bufAppendC(' ');

    shExpr(p->u.print_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Stm!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void shInteger(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void shIdent(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

