/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef PRINTER_HEADER
#define PRINTER_HEADER

#include "Absyn.h"

/* Certain applications may improve performance by changing the buffer size */
#define BUFFER_INITIAL 2048
/* You may wish to change _L_PAREN or _R_PAREN */
#define _L_PAREN '('
#define _R_PAREN ')'

/* The following are simple heuristics for rendering terminals */
/* You may wish to change them */
void renderCC(Char c);
void renderCS(String s);
void indent(void);
void backup(void);
void onEmptyLine(void);
void removeTrailingSpaces(void);
void removeTrailingWhitespace(void);


char *printExpr(Expr p);
char *printTerm(Term p);
char *printFactor(Factor p);
char *printStm(Stm p);

void ppExpr(Expr p, int i);
void ppTerm(Term p, int i);
void ppFactor(Factor p, int i);
void ppStm(Stm p, int i);

char *showExpr(Expr p);
char *showTerm(Term p);
char *showFactor(Factor p);
char *showStm(Stm p);

void shExpr(Expr p);
void shTerm(Term p);
void shFactor(Factor p);
void shStm(Stm p);

void ppInteger(String s, int i);
void ppIdent(String s, int i);
void ppString(String s, int i);
void shInteger(String s);
void shIdent(String s);
void shString(String s);
void ppInteger(Integer n, int i);
void ppDouble(Double d, int i);
void ppChar(Char c, int i);
void ppString(String s, int i);
void ppIdent(String s, int i);
void shInteger(Integer n);
void shDouble(Double d);
void shChar(Char c);
void shString(String s);
void shIdent(String s);
void bufEscapeS(const char *s);
void bufEscapeC(const char c);
void bufAppendS(const char *s);
void bufAppendC(const char c);
void bufReset(void);
void resizeBuffer(void);

#endif

