/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitExpr(Expr p);
void visitTerm(Term p);
void visitFactor(Factor p);
void visitStm(Stm p);

void visitInteger(Integer p);void visitIdent(Ident p);void visitString(String p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

